--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MulqiGaming64/SimiAI
build-by-default: true
branches:
- main
projects:
  SimiAI:
    path: ""
    libs:
      - src: andresbytes/EasyUI/libEasyUI
        version: 1.0.0
...
