--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MulqiGaming64/SimiAI
build-by-default: true
branches:
  - master
projects:
  SimiAI:
    path: ""
    icon: "icon.png"
    libs:
      - src: GiantQuartz/EasyUI/libEasyUI
        version: 1.0.0
...